name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main  # o la rama que estés usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar MkDocs Material
        run: pip install mkdocs-material

      - name: Construir documentación
        run: mkdocs build
        working-directory: proyecto

      - name: Desplegar en GitHub Pages
        run: mkdocs gh-deploy --force
        working-directory: proyecto
